image:
  repository: fuzzybaird/demo-sa-auth-test-service
  tag: latest
  pullPolicy: IfNotPresent
health:
  path: /liveness
  liveness:
    path: /liveness
    port: 8080
  readiness:
    path: /readiness
    port: 8080
