image:
  repository: fuzzybaird/demo-sa-auth-test-service
  tag: latest
  pullPolicy: IfNotPresent
health:
  path: /liveness
  liveness:
    path: /liveness
    port: 8080
  readiness:
    path: /readiness
    port: 8080

authz: #remove array when uncommenting
  - route: '/publicinfo/*'
    groups: ['Everyone']
    verbs: ['GET']
  - route: '/divisions/weatherby/*'
    groups: ['SuperAdmins', 'TEST_CONNECT_REP']
    verbs: ['GET', 'POST', 'PATCH', 'PUT', 'DELETE']