environment: development

resources:
  limits:
    memory: "1024Mi"
  requests:
    memory: "512Mi"

health:
  path: '/actuator/health'

configMapKeys:
  - name: KAFKA_HOSTS
    keymap: kafka-cluster-config
    key: broker.tls.endpoints
