environment: development
envs: 
  - name: BOX_URL
    value: https://somebox.url
  - name: BOX_KEY
    value: 12345
  - name: BOX_SECRET
    value: boxdev

configMapKeys:
  - name: MY_ENV_VAR
    keymap: some-configmap-name
    key: configmap.key

configMaps:
  - name: some-configmap-name

auth:
  _default:
    enabled: false