---
apiVersion: v1
kind: Endpoints
metadata:
  name: {{ .Values.name }}
  labels:
    helm.sh/chart: {{ printf "%s-%s" .Chart.Name .Chart.Version | replace "+" "_" | trunc 63 | trimSuffix "-" }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
subsets:
  - addresses:
      {{- range .Values.ips }}
      - ip: {{ . }}
      {{- end }}
    ports:
      {{- range .Values.ports }}
      - port: {{ . }}
      {{- end }}

