---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.name }}
  labels:
    helm.sh/chart: {{ printf "%s-%s" .Chart.Name .Chart.Version | replace "+" "_" | trunc 63 | trimSuffix "-" }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  ports:
    {{- range .Values.ports }}
    - protocol: TCP
      port: {{ . }}
      targetPort: {{ . }}
    {{- end }}
