{{- $istiogateway := printf "%s" (include "service.istiogateway" .) -}}
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: {{ .Release.Name }}
spec:
  hosts:
  - "{{ .Release.Name }}.{{ .Release.Namespace }}.platform.aws.chgit.com"
  gateways:
  - "{{ .Release.Namespace }}-gateway"
  http:
  - route:
    - destination:
        host: {{ include "service.fullname" . }}
        port:
          number: {{ .Values.service.port }}
