### For Creating a ECR Repo using the Platform aws-ecr terraform Module
## aws-ecr Module Source Repo: https://github.com/chghealthcare/terraform-chg-aws-ecr
ecr-workspace:
  # Workspace configuration settings
  workspace:
    module:
      name: aws-ecr
      version: 1.0.3

## Add Below to values.yaml overrides and set the enabled to true to enable this Module
#ecr-workspace:
#  workspace:
#    name: <workspace name>
#    module:
#      config:
#        version: <version>
#        # ECR Config Settings example
#        repos:
#        - name: demo-service2
#          maxImageCount: 10
#          scanImagesOnPush: false
#          tags:
#          - key: environment
#            value: nonprod