{{- $istiogateway := printf "%s" (include "service.istiogateway" .) -}}
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: {{ .Release.Name }}
spec:
  hosts:
  - "{{ .Release.Name }}.{{$istiogateway}}"
  gateways:
  - {{ .Release.Name }}
  http:

  - route:
    - destination:
        host: {{ include "service.fullname" . }}
        port:
          number: {{ .Values.service.port }}
