# Default values for service.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

project: ''


image:
  repository: # [REQUIRED]
  tag: stable # [REQUIRED]
  pullPolicy: IfNotPresent

feature: ''

nameOverride: ''
fullnameOverride: ''

# [REQUIRED]
# This is a required field
# options [development, stage, production]
environment: 'production'

# Database Type. Default to no database. 
#
# options [neo4j, mysql, postgres]
databasetype: ''

# This is only needed if you want to implicitly override your ephemeral feature branch database
# This does not affect your production database type right now.
databaseimage: 

# We include the option to overide the environment variable for backwards
# compatability, but please use the environment variable above.
# NODE_ENV: 'stage'

# These service fields are to map the container's service to the pod. Please note
# that this chart uses Istio so the virtual service also relies on these values.
service:
  type: IPCluster
  port: 8232
  target: 8080

# The health variables are currently used in the test-connection yaml to help
# determine whether your service is up and running.
health:
  path: '/health'

# [REQUIRED]
# Each deployment gets its own gateway that maps through the virtual service
# into the service and finally into the pod.
istiogateway:
  _default: 'dev.cs.aws.chgit.com'
  stage: 'dev.cs.aws.chgit.com'
  production: 'prod.cs.aws.chgit.com'

# The default values here are: 
auth:
  _default:
    enabled: true
    issuer: 'https://chghealthcare.oktapreview.com/oauth2/auskmtjacfEi8ffM60h7'
    jwks: 'https://chghealthcare.oktapreview.com/oauth2/auskmtjacfEi8ffM60h7/v1/keys'
    forwardOriginalToken: true
  stage:
    enabled: true
    issuer: 'https://chghealthcare.oktapreview.com/oauth2/auskmtjacfEi8ffM60h7'
    jwks: 'https://chghealthcare.oktapreview.com/oauth2/auskmtjacfEi8ffM60h7/v1/keys'
    forwardOriginalToken: true
  production:
    enabled: true
    issuer: 'https://chghealthcare.okta.com/oauth2/aus46u1vjfkkTfP7d2p7'
    jwks: 'https://chghealthcare.okta.com/oauth2/aus46u1vjfkkTfP7d2p7/v1/keys'
    forwardOriginalToken: true


envs: []
# - name: ENVIRONMENT
#   value: production
# - name: CAT
#   value: Man

# secrets -- Creates a secret for the application. All variables passed in env.
# Uses envFrom in the deployment specification to pass these all through.
secretRefs: []
# - global-one

secretKeyRefs: []
# - name: YOUR_ENV_VAR
#   secret: secret-store-name
#   key: secret-key

configMaps: []
# - some-configmap-name

configMapKeys: []
# - name: YOUR_ENV_VAR
#   keymap: config-map-name
#   key: key-from-config-map

ingress:
  enabled: false
  annotations: {}
    # kubernetes.io/ingress.class: nginx
    # kubernetes.io/tls-acme: 'true'
  hosts:
    - host: 
      paths: []

  tls: []
  #  - secretName: chart-example-tls
  #    hosts:
  #      - chart-example.local
# '977624198390.dkr.ecr.us-west-2.amazonaws.com/neo4j:latest'
resources: {}
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with minimal
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  # limits:
  #   cpu: 1
  #   memory: 2048Mi
  # requests:
  #   cpu: 750m
  #   memory: 1024Mi

nodeSelector: {}

tolerations: []

affinity: 
  nodeAffinity:
    requiredDuringSchedulingIgnoredDuringExecution:
      nodeSelectorTerms:
      - matchExpressions:
        - key: worker-type
          operator: NotIn
          values:
          - jenkins-workers

persistentVolumeClaim: {}
  # This should only be used if a claim does not already exist.  If there is a pre-existing 
  # claim (e.g. an existing shared volume), you need only attach a persistentVolume (below)
  # and reference the name of the existing claim.
  # enabled: false 
  # size: 2Gi
  # name: px-test-shared
  # type: shared # Valid options: shared, secure, postgres
  # mode: ReadWriteMany # IMPORTANT: for any type other than "shared" the mode should be set to ReadWriteOnce

persistentVolume: {}
  # Mount a volume from a persistentVolumeClaim.  If not using a pre-existing claim, you must
  # also enable a new persistentVolumeClaim (above) and reference it by name (claimName) here
  # attach: false
  # claimName: px-text-shared
  # volumeName: data
  # mountPath: /data
scaling:
  minReplicas: 2
  maxReplicas: 4
  averageCpuUtilization: 50

# This value is what sets the annotation on deployed resources for auto 
# clean up in our enabled environments IE: Feature Namespace. If you need
# your service to stay up longer you can set this to your needs.
cleanUpIn: 48h