{{- $auth := pluck .Values.environment .Values.auth | first | default .Values.auth._default -}}
{{- $authGlobal := pluck .Values.environment .Values.authGlobal | first | default .Values.authGlobal._default -}}
{{ if or (eq $auth.enabled true) (eq .Values.authEnabled true) -}}
---
apiVersion: security.istio.io/v1beta1
kind: RequestAuthentication
metadata:
  name: {{ include "service.fullname" . }}-rqauth
  labels:
{{ include "service.commonLabels" . | indent 4 }}
  annotations:
    {{- if .Values.cleanUpIn }}
    janitor/ttl: {{ .Values.cleanUpIn }}
    {{- end }}
spec:
  selector:
    matchLabels:
      app.kubernetes.io/instance: {{ .Release.Name }}
      app.kubernetes.io/name: {{ include "service.name" . }}
  jwtRules:
  - issuer: {{ $auth.issuer }}
    jwksUri: {{ $auth.jwks }}
    forwardOriginalToken: {{ $auth.forwardOriginalToken }}
  - issuer: {{$authGlobal.issuer}}
    jwksUri: {{ $authGlobal.jwks }}
    forwardOriginalToken: true

---
apiVersion: security.istio.io/v1beta1
kind: AuthorizationPolicy
metadata:
  name: {{ include "service.fullname" . }}-auth-policy
spec:
  selector:
    matchLabels:
      app.kubernetes.io/instance: {{ .Release.Name }}
      app.kubernetes.io/name: {{ include "service.name" . }}
  action: ALLOW
  rules:
{{- range .Values.authz }}
  - from:
    - source:
        principals: ["*"]
    to:
      - operation:
          methods: {{ .verbs | toJson }}
          paths: 
            - {{ .route | quote }}
    when:
      - key: request.auth.claims[groups]
        values: {{ .groups | toJson }}
{{- end }}
  - from:
    - source:
        requestPrincipals: ["{{ $auth.issuer }}/*","{{ $authGlobal.issuer }}/*"]
    - source:
        namespaces: ["{{ .Release.Namespace }}"]
  - to:
    - operation:
        methods:
        - "GET"
        {{ range .Values.istioAllowedMethods }}
        - {{ . | quote }}{{ end }}
        paths:
        - "/liveness"
        - "/readiness"
        - "{{ .Values.health.liveness.path }}"
        - "{{ .Values.health.readiness.path }}"
        - "/"
        - "/docs"
        - "/docs/*"
        - "/swagger-ui/*"
        {{ range .Values.istioAllowedPaths }}
        - {{ . | quote }}{{ end }}

{{- end -}}
