{{- $istiogateway := printf "%s" (include "service.istiogateway" .) -}}
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: {{ .Release.Name }}
  annotations:
    {{- if .Values.cleanUpIn }}
    janitor/ttl: {{ .Values.cleanUpIn }}
    {{- end }}
spec:
  hosts:
  - "{{ .Release.Name }}.{{ .Release.Namespace }}.platform.aws.chgit.com"
  gateways:
  - "{{ .Release.Namespace }}-gateway"
  http:
  - route:
    - destination:
        host: {{ include "service.fullname" . }}
        port:
          number: {{ .Values.service.port }}
{{ if .Values.istiogateway.corsPolicy }}
    corsPolicy:
      allowOrigin: {{ range .Values.istiogateway.corsPolicy.allowOrigin }}
      - {{ . | quote }}{{ end }}
      allowMethods: {{ range .Values.istiogateway.corsPolicy.allowMethods }}
      - {{ . | quote }}{{ end }}
      allowCredentials: {{ .Values.istiogateway.corsPolicy.allowCredentials }}
      allowHeaders: {{ range .Values.istiogateway.corsPolicy.allowHeaders }}
      - {{ . | quote }}{{ end }}
      maxAge: {{ .Values.istiogateway.corsPolicy.maxAge }}
{{ end }}
