{{ $root := . }}
{{ range $index, $job := $root.Values.jobs }}
{{ $hookAnnotations := index $job.annotations "helm.sh/hook" }}
---
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ include "service.fullname" $root }}-job-{{ $index }}
  {{ if $job.annotations }}
  labels:
{{ include "service.commonLabels" $root | indent 4 }}
  annotations:
    {{ range $key, $val := $job.annotations }}
    {{ $key }}: {{ $val }}
    {{ end }}
    {{- if $root.Values.cleanUpIn }}
    janitor/ttl: {{ $root.Values.cleanUpIn }}
    {{- end }}
  {{ end }}
spec:
  backoffLimit: {{ $job.backoffLimit }}
  template:
    metadata:
      annotations:
        "sidecar.istio.io/inject": "false"
    spec:
      containers:
      - name: {{ $job.containerName }}
        image: {{ $job.image }}
        command: {{ range $job.command }}
        - {{ . | quote }}{{ end }}
        env:
          {{- range $root.Values.envs }}
            - name: {{ .name | quote }}
              value: {{ .value | quote }}
          {{- end }}
          {{- range $root.Values.kafkaTopics }}
            - name: {{ .envKey | quote }}
              value: {{ if $root.Values.feature }}{{ printf "%s-%s" $root.Values.feature .name }}{{ else }}{{ .name }}{{ end }}
          {{- end }}
          {{- range $root.Values.configMapKeys }}
            - name: {{ .name | quote}}
              valueFrom:
                configMapKeyRef:
                    name: {{ .keymap | quote }}
                    key: {{ .key | quote }}
          {{- end }}
          {{- range $root.Values.secretKeys }}
            - name: {{ .name | quote }}
              valueFrom:
                secretKeyRef:
                    name: {{ .secret | quote }}
                    key: {{ .key | quote }}
          {{- end }}
          {{- range .envs }}
            - name: {{ .name | quote }}
              value: {{ .value | quote }}
          {{- end }}
        envFrom:
          {{- if $root.Values.pullVaultSecrets }}{{- if not (contains "pre-install" $hookAnnotations) }}{{- if not (contains "pre-upgrade" $hookAnnotations) }}
          - secretRef:
              name: {{ include "service.fullname" $root | quote }}
          {{- end }}{{- end }}{{- end }}
          {{- range $root.Values.secretRefs }}
            - secretRef:
                name: {{ . | quote }}
          {{- end }}
          {{- range $root.Values.configMaps }}
            - configMapRef:
                name: {{ . | quote }}
          {{- end }}
      restartPolicy: Never

{{ end }}
