{{ $root := . }}
{{ range $index, $watcher := .Values.kibanaWatchers }}
---
apiVersion: alert.my.domain/v1alpha1
kind: KibanaWatcher
metadata:
  name: {{ include "service.fullname" $root }}-{{ $watcher.name }}-{{ $root.Release.Namespace }}
  labels:
{{ include "service.commonLabels" $root | indent 4 }}
  annotations:
    {{- if $root.Values.cleanUpIn }}
    janitor/ttl: {{ $root.Values.cleanUpIn }}
    {{- end }}
spec:
  definition: |
    {{ $watcher.definition | toJson | indent 4 }}

{{ end }}
