{{ if eq .Values.persistentVolumeClaim.enabled true -}}
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
   name: {{ .Values.persistentVolumeClaim.name }}
   annotations:
     volume.beta.kubernetes.io/storage-class: px-{{ .Values.persistentVolumeClaim.type }}-sc
spec:
   accessModes:
     - ReadWriteMany
   resources:
     requests:
       storage: {{ .Values.persistentVolumeClaim.size }}
