{{ if .Values.persistentVolumeClaim -}}
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
   name: {{ .Values.persistentVolumeClaim.name }}
   annotations:
     volume.beta.kubernetes.io/storage-class: px-{{ .Values.persistentVolumeClaim.type }}-sc
   labels:
     app.kubernetes.io/name: {{ include "service.name" . }}
spec:
   accessModes:
     - {{ .Values.persistentVolumeClaim.mode }}
   resources:
     requests:
       storage: {{ .Values.persistentVolumeClaim.size }}
{{end}}
