{{ if .Values.persistentVolumeClaim -}}
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: {{ .Values.persistentVolumeClaim.name }}
  labels:
{{ include "service.commonLabels" . | indent 4 }}
  annotations:
    volume.beta.kubernetes.io/storage-class: px-{{ .Values.persistentVolumeClaim.type }}-sc
    {{- if .Values.cleanUpIn }}
    janitor/ttl: {{ .Values.cleanUpIn }}
    {{- end }}
spec:
   accessModes:
     - {{ .Values.persistentVolumeClaim.mode }}
   resources:
     requests:
       storage: {{ .Values.persistentVolumeClaim.size }}
{{end}}
