apiVersion: "acid.zalan.do/v1"
kind: postgresql
metadata:
  name: {{ printf "%s-%s" .Values.postgres.teamId .Values.postgres.clusterName }} 
  namespace: {{ if eq .Release.Namespace "prod" }} database {{ else printf "%s-database" .Release.Namespace }} {{ end }}
spec:
  teamId: {{ quote .Values.postgres.teamId }} 
  volume:
    size: {{ .Values.postgres.size }} 
    storageClass: px-postgres-sc
  numberOfInstances: {{ .Values.postgres.numberOfInstances }}
  users:
    # database owner
    sreadmin:
    - superuser
    - createdb

    # role for application foo
    foo_user: # or 'foo_user: []'

  #databases: name->owner
  databases:
    {{ .Values.postgres.dbName }}: {{ .Values.postgres.owner }}
  postgresql:
    version: {{ quote .Values.postgres.version }} 
  
  nodeAffinity:
  requiredDuringSchedulingIgnoredDuringExecution:
    nodeSelectorTerms:
      - matchExpressions:
          - key: px/enabled
            operator: NotIn
            values:
              - "false"
