{{ if .Values.postgres }}
{{ $root := . }}
{{ $teamId := .Values.postgres.teamId }}
{{ $dbName := .Values.postgres.dbName }}
{{ $dbOwner := .Values.postgres.owner }}
{{ $releaseNamespace := .Release.Namespace }}
{{ $dbClusterName := printf "%s-%s" $teamId $dbName }}
{{ $dbOwnerSecret := printf "%s.%s" $dbOwner $dbClusterName }}
{{ if $root.Values.feature }}
{{ $dbClusterName = printf "%s-%s-%s" $teamId $root.Values.feature $dbName }}
{{ $dbOwnerSecret = printf "%s.%s" $dbOwner $dbClusterName }}
{{ end }}

{{ $dbNamespace := printf "%s-database" $releaseNamespace }}
---
apiVersion: "acid.zalan.do/v1"
kind: postgresql
metadata:
  name: {{ $dbClusterName }}
  namespace: {{ $dbNamespace }}
  labels:
{{ include "service.commonLabels" . | indent 4 }}
  annotations:
    {{- if .Values.cleanUpIn }}
    janitor/ttl: {{ .Values.cleanUpIn }}
    {{- end }}
spec:
  teamId: {{ quote $teamId }}
  volume:
    size: {{ .Values.postgres.size }}
    storageClass: px-postgres-sc
  numberOfInstances: {{ .Values.postgres.numberOfInstances }}
  users:
    # database owner
    {{ $dbOwner }}:
    - superuser
    - createdb

  #databases: name->owner
  databases:
    {{ $dbName }}: {{ $dbOwner }}
  postgresql:
    version: {{ quote .Values.postgres.version }}

  nodeAffinity:
    requiredDuringSchedulingIgnoredDuringExecution:
      nodeSelectorTerms:
        - matchExpressions:
            - key: px/enabled
              operator: NotIn
              values:
                - "false"


# Replicated Secret from the {Database Namespace}/{dbOwner Secret}
---
apiVersion: v1
kind: Secret
metadata:
  annotations:
    replicator.v1.mittwald.de/replicate-from: {{ $dbNamespace }}/{{ $dbOwnerSecret }}
  labels:
    cluster-name: {{ $dbClusterName }}
    team: {{ $teamId }}
  name: {{ $dbOwnerSecret }}
  namespace: {{ $releaseNamespace }}
data: {}


{{- if or (eq .Values.environment "stage") (eq .Values.environment "prod")}}
# Postgres DB application backup schedule spec
---
apiVersion: stork.libopenstorage.org/v1alpha1
kind: ApplicationBackupSchedule
metadata:
  name: {{ printf "%s-daily-backup" $dbClusterName }}
  namespace: {{ $dbNamespace }}
spec:
  reclaimPolicy: Retain
  schedulePolicyName: default-daily-policy
  template:
    spec:
      backupLocation: s3backup-default
      namespaces:
      - {{ $dbNamespace }}
      postExecRule: ""
      preExecRule: ""
      reclaimPolicy: Retain
      selectors:
      - cluster-name: {{ $dbClusterName }}
      
{{- end }}
{{ end }}
