{{ if .Values.postgres }}
{{ $teamId := .Values.postgres.teamId }}
{{ $dbName := .Values.postgres.dbName }}
{{ $dbOwner := .Values.postgres.owner }}
{{ $releaseNamespace := .Release.Namespace }}
{{ $dbClusterName := printf "%s-%s" $teamId $dbName }}
{{ $dbOwnerSecret := printf "%s.%s" $dbOwner $dbClusterName }}
{{ $dbNamespace := printf "%s-database" $releaseNamespace }}
apiVersion: "acid.zalan.do/v1"
kind: postgresql
metadata:
  name: {{ $dbClusterName }}
  namespace: {{ $dbNamespace }}
spec:
  teamId: {{ quote $teamId }}
  volume:
    size: {{ .Values.postgres.size }} 
    storageClass: px-postgres-sc
  numberOfInstances: {{ .Values.postgres.numberOfInstances }}
  users:
    # database owner
    {{ $dbOwner }}:
    - superuser
    - createdb

  #databases: name->owner
  databases:
    {{ $dbName }}: {{ $dbOwner }}
  postgresql:
    version: {{ quote .Values.postgres.version }} 
  
  nodeAffinity:
  requiredDuringSchedulingIgnoredDuringExecution:
    nodeSelectorTerms:
      - matchExpressions:
          - key: px/enabled
            operator: NotIn
            values:
              - "false"


# Replicated Secret from the {Database Namespace}/{dbOwner Secret}
---
apiVersion: v1
kind: Secret
metadata:
  annotations:
    replicator.v1.mittwald.de/replicate-from: {{ $dbNamespace }}/{{ $dbOwnerSecret }}
  labels:
    cluster-name: {{ $dbClusterName }}
    team: {{ $teamId }}
  name: {{ $dbOwnerSecret }}
  namespace: {{ $releaseNamespace }}
data: {}

{{ end }}
