{{ if .Values.redis }}
---
apiVersion: k8s.amaiz.com/v1alpha1
kind: Redis
metadata:
  name: {{ include "service.redisFullname" . }}
  namespace: {{ .Release.Namespace }}-database
  labels:
    cluster-name: {{ include "service.redisFullname" . }}
{{ include "service.commonLabels" . | indent 4 }}
  annotations:
    {{- if .Values.cleanUpIn }}
    janitor/ttl: {{ .Values.cleanUpIn }}
    {{- end }}
spec:
  # required field. Minimum value is 3
  replicas: {{ .Values.redis.replicas }}
  {{ if .Values.redis.config }}
  config:
    {{ range $key, $value := .Values.redis.config }}
    {{ $key }}: {{ $value | quote }}
    {{ end }}
  {{ end }}

  affinity:
    podAntiAffinity:
      preferredDuringSchedulingIgnoredDuringExecution:
      - podAffinityTerm:
          labelSelector:
            matchExpressions:
            - key: cluster-name
              operator: In
              values:
              - {{ include "service.redisFullname" . }}
          topologyKey: kubernetes.io/hostname
        weight: 70
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
        - matchExpressions:
          - key: px/enabled
            operator: In
            values:
            - "false"
        - matchExpressions:
          - key: NodeType
            operator: In
            values:
            - "general-purpose"
  redis:
    image: redis:5-alpine
    initialDelaySeconds: 10
    resources:
      limits:
        cpu: 100m
        memory: 200Mi
    securityContext:
      allowPrivilegeEscalation: false
      capabilities:
        drop:
        - all
      readOnlyRootFilesystem: true
      runAsUser: 7777777
      runAsGroup: 7777777
      fsGroup: 7777777
      runAsNonRoot: true
  exporter:
    image: oliver006/redis_exporter:v1.2.1
    resources:
      limits:
        cpu: 50m
        memory: 100Mi
    securityContext:
      allowPrivilegeEscalation: false
      capabilities:
        drop:
        - all
      readOnlyRootFilesystem: true
      runAsUser: 7777777
      runAsGroup: 7777777
      fsGroup: 7777777
      runAsNonRoot: true
{{ end }}
