apiVersion: v1
kind: Service
metadata:
  name: {{ include "service.fullname" . }}
  labels:
{{ include "service.commonLabels" . | indent 4 }}
  annotations:
    {{- if .Values.cleanUpIn }}
    janitor/ttl: {{ .Values.cleanUpIn }}
    {{- end }}
spec:
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.target }}
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: {{ include "service.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
