{{ if .Values.pullVaultSecrets }}
{{- $environment := printf "%s" (include "service.environment" .) -}}
apiVersion: "koudingspawn.de/v1"
kind: Vault
metadata:
  name: {{ include "service.fullname" . }}
  labels:
{{ include "service.commonLabels" . | indent 4 }}
  annotations:
    {{- if .Values.cleanUpIn }}
    janitor/ttl: {{ .Values.cleanUpIn }}
    {{- end }}
    argocd.argoproj.io/compare-options: IgnoreExtraneous
spec:
  path: "{{ include "service.environmentShort" . }}/{{ .Values.project }}"
  type: "KEYVALUEV2"
{{ end }}
