apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/name: {{ .Release.Name }}
    helm.sh/chart: {{ .Chart.Name }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
  annotations:
    reloader.stakater.com/auto: "true"
  name: {{ .Release.Name }}
  namespace: {{ .Release.Namespace }}
spec:
  replicas: {{ .Values.replicas | default 1 }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ .Release.Name }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ .Release.Name }}
        app.kubernetes.io/instance: {{ .Release.Name }}
      annotations:
        sidecar.istio.io/inject: "false"
    spec:
      imagePullSecrets:
      - name: github-registry
      containers:
      - name: {{ .Release.Name }}
        image: "{{ .Values.image.name }}:{{ .Values.image.tag }}"
        imagePullPolicy: 'IfNotPresent'
        ports:
          - name: http
            containerPort: {{ .Values.port | default 80 }}
            protocol: TCP
        {{- if .Values.env }}
        env:
        {{- range $key, $val := .Values.env }}
          - name: {{ $key | quote }}
            value: {{ $val | quote }}
        {{- end }}
        {{- end }}
        {{- if .Values.secrets.refs }}
        envFrom:
          {{ if .Values.secrets.vaultPullSecrets }}
          {{- range $i, $val := .Values.secrets.vaultPullSecrets }}
          - secretRef:
              name: {{ $val.ref | quote }}
          {{- end }}
          {{- end }}
          {{- range $i, $val := .Values.secrets.refs }}
          - secretRef:
              name: {{ $val | quote }}
          {{- end }}
        {{- end }}
        resources:
        {{- .Values.resources | toYaml | nindent 12 }}
        livenessProbe:
          httpGet:
            path: '/'
            port: {{ .Values.port | default 80 }}
          initialDelaySeconds: 5
          periodSeconds: 30
        readinessProbe:
          httpGet:
            path: '/'
            port: {{ .Values.port | default 80 }}
          initialDelaySeconds: 5
          periodSeconds: 10

