apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  labels:
    app.kubernetes.io/name: {{ .Release.Name }}
    helm.sh/chart: {{ .Chart.Name }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
  name: {{ .Release.Name }}
spec:
  hosts:
  - "{{ .Release.Name }}.{{ .Release.Namespace }}.platform.aws.chgit.com"
  gateways:
  - "{{ .Release.Namespace }}-gateway"
  http:
  - route:
    - destination:
        host: {{ .Release.Name }}
        port:
          number: {{ .Values.port | default 80 }}
