apiVersion: v1
data:
  FROM_HOST: {{ .Values.databases.from.host }}
  FROM_USER: {{ .Values.databases.from.user }}
  FROM_PASS: {{ .Values.databases.from.pass }}
  FROM_DB: {{ .Values.databases.from.database }}
  TO_HOST: {{ .Values.databases.to.host }}
  TO_USER: {{ .Values.databases.to.user }}
  TO_PASS: {{ .Values.databases.to.pass }}
  TO_DB: {{ .Values.databases.to.database }}
kind: Secret
type: Opaque
metadata:
  annotations:
    app.kubernetes.io/name: {{ .Release.Name }}
    helm.sh/chart: {{ .Chart.Name }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
  name: {{ .Release.Name }}
  namespace: {{ .Release.Namespace }}
