name: Release Charts

on:
  push:
    branches:
      - master
      - 'feature/add-chart-museum-action'

jobs:
  release:
    runs-on: self-hosted

    strategy:
      matrix:
        charts:
        - 'database-migrator'
        - 'service'
        - 'worker'

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - uses: goodsmileduck/helm-push-action@v2
        env:
          SOURCE_DIR: 'charts'
          CHART_FOLDER: ${{ matrix.charts }}
          FORCE: 'True'
          CHARTMUSEUM_URL: 'https://chartmuseum.shared.aws.chgit.com'
          CHARTMUSEUM_USER: '${{ secrets.CHARTMUSEUM_USERNAME }}'
          CHARTMUSEUM_PASSWORD: ${{ secrets.CHARTMUSEUM_PASSWORD }}
